### ISSUE TITLE
Allow the use of pre-built binaries

### ISSUE THREAD

**Issue by vlsi** [nokeedev/gradle-native#13]
Building native binaries require the installation of the relevant toolchain.
The toolchains are not always installed, and, apparently, it is not possible to install both Windows and macOS compilers at the same time.

Do you think it makes sense to figure out the approach to structure the project in such a way that it uses a pre-built file (e.g. downloaded as an artifact) and pretends as if it was a compilation result?

**Comment by lacasseio** [comment]
Great point, it does make sense that you should be able to download pre-built binaries. It should be possible to get decent mileage with Gradle as of now so I will see to write a sample for this. 

Could you give me a bit of context with regards to your specific scenario? 

If you mean running the code locally without building the native code because of missing toolchain, you could either use dependency substitution with included build. Or even conditionally wire the outgoing artifacts to a binary dependency of the latest built library. 

If you are referring to publishing (aka publishing everything in one go) you should be able to publish the pieces that are buildable individually. The downside is the artifact won't be resolvable while the process is being done. In other word it's not atomic with a plain Maven repo. You could use Bintray to upload unpublished artifact and publish them in one go or have one job in the CI that gather all the built binaries for publication.

**Comment by vlsi** [comment]
Well, the case is still https://github.com/weisJ/darklaf

I'm not sure dependency substitution is suitable to replace `compileCpp/link` tasks in a JNI module.

In other words, the use cases are:
1) Being able to build and use native binaries on a machine where the compiler is not installed.
For instance, a user wants to build/test the project, however, they do not have xcode installed.
In most cases, the old binary is still workable with the current Java code. The user can even add logging to Java part of the JNI and still lauch the project.

2) Release. Non-atomic releases are complicated. Of course one of the solutions might be factoring out platform-related module to its own build and release cycle, however, monorepo-like approach simplifies maintenance.
For instance, I happen to maintain a couple of loosely-coupled Gradle plugins, and it is way easier to [keep them in a single repository](https://github.com/vlsi/vlsi-release-plugins) and release all of them at once even though I don't modify them always together.

The same thing with JNI. https://github.com/weisJ/darklaf/tree/master/macos contains both C++ native code and Java code (which is not just C++ wrapper, but there is Swing-related Java code).
`darklaf-macos` module depends on the common code (e.g. `darklaf-decorations-base`), so factoring out "just darklaf-macos jni library" would be complicated.

That is why I'm more inclined to a case when a prebuilt library can be reused instead of trying to execute C++ compiler.

PS. I know I can add the logic to the build script itself, however, I guess having conventions might be helpful there.

**Comment by lacasseio** [comment]
Hmmm, I see your point. With Gradle there are multiple ways this could be achieved. I'm trying to figure out if it should be 1) a core feature, 2) a configuration to the project, or 3) allow more composition of a JNI library so you can compose the variants however you want. I tried to make a clear distinction of between unknown, unsupported and unbuildable target machines:
- Unknown: Gradle has no knowledge of the target machines event exists.
- Unsupported: Gradle knows about the target machines but it's unsupported for the current host
- Unbuildable: Gradle knows about the target machines and it could be built on the current host but you don't have the compilers/tools.

At the moment, we crash for the unknown target machine, ignores unsupported target machine, but still create the unbuildable variant as well as wiring them which causes a failure. A possible scenario that could make sense for **testing only** is if the variant is unbuildable for your host we simply warn and still allow you to execute the tests in Java. However, it may be surprising for some users.

Your ideal scenario seems more toward "build from source if you can or pull the prebuilt binary if you can't". It seems to overlap with what caching would but reversed: "if it's already built, pull it from cache, else build it from source". The reason being that if the code changes, then a user may be surprised the code isn't recompiled. Instead, it would simply fail saying "hey, we can't build this because you don't have the compiler and the cache doesn't have a version of this code built".

I think the next step for this would be to see if the caching would solve the unbuildable issue. If it does, a guide teaching how to set up caching for natives with a focus on this scenario would be best and show the least surprise to the users. As an alternative, we could also demonstrate a poor-man caching by configuring the wiring for this specific use case as a sample. It's a poor-man simply because it's mostly an approximation of correctness which may become false when the native code change. It is possible to notify the user when that happens. I personally would be more interested in a guide showing how to configure caching to optionally build binaries, especially when the binaries aren't buildable. What do you think?

**Comment by vlsi** [comment]
Well, `build cache` might indeed cover most of the use cases.

However, it might be problematic:
* poor man's build cache might be not that very available (e.g. offline mode or just availability issues)
* It is not clear how to manage grants to pushing the binaries to the build cache. Can I allow to push just one file?

It looks like the way to go here is trying to structure JNI library as a small wrapper, so it could be its own artifact.
Then, that library could be pushed to Central / JCenter as a regular artifact and reused (e.g. project dependency replaced with a regular artifact from Central).

**Comment by lacasseio** [comment]
Sounds good, let me see what samples I can come up to help address this use case.

**Comment by lacasseio** [comment]
On second though the task output caching will not work as it's too fine grain for this specific issue. We should have a better way to fingerprint the system library. Currently, it needs the files/compilers to be present before it can pull the cached files. We should evolve toward pulling the cached files based on what Gradle assumed should be present for building the code. This means, instead of saying "here are the headers and compiler that we are going to use, is it already built", we should be saying "we should be using the headers from X library and the compilers from Y, is it already built". A lot of modelling will be required for this to work so it's unlikely to happen soon. However, we can probably shortcut some it this but using prebuilt libraries from a Maven library as you said. Let's focus on a sample that accomplishes that.

**Comment by vlsi** [comment]
One more thought: sometimes the compiler might be downloaded from somewhere during the build.
For instance, one can download `node.js` binary during Gradle build.

However, that does not work since Xcode can't be downloaded/installed in an unattended mode.

**Comment by lacasseio** [comment]
I created this sample issue: https://github.com/nokeedev/gradle-native/issues/16. It should be possible to demonstrate without any new features.

**Comment by lacasseio** [comment]
I agree that toolchain provisioning is something of the ideal world. I have a couple of idea on how to do this but currently, it's a bit troublesome with the compiler backend inside the core of Gradle. There are a couple of things I need to experiment with before I can select a plan for this.

It is true that Xcode is a bit complicated for unattended mode. An organization could pre-download the distribution into an S3 bucket for example and then let a capability within the plugins to provision the XIP file. It may be possible to authenticate on the developer.apple.com portal and pull the binary directly from there but I fear such a feature would be very fragile. Another way is to use GCC or Clang from Homebrew (or the like), you can see a [never released sample for this here](https://github.com/gradle/native-samples/tree/lacasseio/improve-provisionable-toolchains/cpp/provisionable-tool-chains)

**Comment by lacasseio** [comment]
With some recent change coming to 0.4, this use case is much simpler to solve as demonstrated in auto-dark-mode project: https://github.com/lacasseio/auto-dark-mode/blob/58dee93ba45338606f7e78df595d50fc6d6d69e0/buildSrc/src/main/groovy/UsePrebuiltBinariesWhenUnbuildablePlugin.groovy#L9-L27

We should create a sample showing how to solve this. We should also add a bit of explanation in the JNI chapter introducing `nativeRuntimeFiles` and how it contains implicit task dependencies and that users can overwrite the list of native runtime files to shortcut the native build process is they want.

**Comment by lacasseio** [comment]
The original scenario regarding using pre-built binaries instead of building from the source is completely possible with the 0.4 APIs. It's also quite easy to accomplish as demonstrated in this [new sample](https://github.com/nokeedev/gradle-native/blob/master/subprojects/docs/src/docs/samples/jni-library-with-pre-built-binaries/groovy-dsl/build.gradle#L23-L31).

@vlsi I would be ready to close this issue. Could you input on the sample? I'm looking mainly if you feel it's a proper solution to the use case. A more real-life usage is can be found [in auto-dark-mode](https://github.com/lacasseio/auto-dark-mode/blob/58dee93ba45338606f7e78df595d50fc6d6d69e0/buildSrc/src/main/groovy/UsePrebuiltBinariesWhenUnbuildablePlugin.groovy) which I assume will be migrated to darklaf.

As for the atomic release use-case, I opened the issue https://github.com/nokeedev/gradle-native/issues/54.

**Comment by lacasseio** [comment]
I added [another pre-built sample](https://github.com/nokeedev/gradle-native/tree/master/subprojects/docs/src/docs/samples/jni-library-composing-from-pre-built-binaries) that shows a different use case. I will consider this done. Feel free to comment your feedback here.
