### ISSUE TITLE
gradle-native on hpux

### ISSUE THREAD

**Issue by chittiraju** [nokeedev/gradle-native#277]
Hi,
I found the gradle native plugin to be very interesting and next generation build tool.
after seeing what it is capable of on windows and linux, i proposed my team to use gradle instead of cmake for our enterprise application.

But I see there is no support for gradle cpp plugin for hpux, solaris, AIX targetMachines currently.

Is there any workaround or tweak to make basic compilation working on these operating systems?

Need your inputs as soon as possible.

**Comment by lacasseio** [comment]
Great point. We are currently working on improvement around custom variant declaration which would be unblocking other platforms such as Solaris and others. By the end of this month, we should have a better timeline on when it will be conveniently possible. Under the hood, we use the software model toolchain selection so it should be possible to force a custom OS family/architecture. We don't have many tests around this scenario so there may be some underlying issues :-(  Does your build cross-compile to HPUX or the builds run directly on the system? At the moment, it would be relatively easy to configure the toolchains for host build (building on the target machine).

**Comment by chittiraju** [comment]
Thanks for the response.
we dont use cross-compilers. we compile it on host machine itself.

can you help me in configuring toolchain for HPUX if possible with a small sample.

**Comment by lacasseio** [comment]
I will reserve some time tomorrow to look into this. From my very quick research, it seems the HPUX toolchain is a GCC-based toolchain? The exception points at the OS detection logic that is a bit lacking. That is an easy fix. I will post back with some more information.

**Comment by chittiraju** [comment]
yes its OS detection logic only "DefaultOperatingSystem.java" of native platforms plugin.
All of our compilers are based on GCC on different platforms(Linux based, Solaris, AIX, HPUX).

I have one more request..
How do i publish/consumer architecture based artifacts to/from JFROG Artifactory.

I could see all windows and linux being published and consumered directly but we also have different architectures like Suse ppc64,  Suse ppc64le, Debain 64 etc. how to add architect and OS tag to the artifacts

**Comment by lacasseio** [comment]
I created [this PR](https://github.com/nokeedev/gradle-native/pull/287) to move over host detection. However, based on my experimentation, it seems like Gradle core doesn't properly fallback on unsupported platforms (https://github.com/gradle/native-platform#supported-platforms) causing the compiler forking to fail. We could do cross-compilation (from a supported platform). I'm in contract with the Gradle team to figure out a way around this to build on the same host.

As for the publishing and consuming from artifactory, Nokee don't offer out-of-the-box support but it's possible to achieve [using custom publishing component](https://docs.gradle.org/current/userguide/publishing_customization.html#sec:publishing-custom-components). There are a couple of question to answer first to properly model the publishing with custom publishing components. This approach will work for any Maven/Ivy repositories.

I'm assuming the architect and OS tag on artifact refers to JFrog artifactory feature which would be an additional step to execute post publishing. I could be possible to use directly JFrog publishing plugin but I can't say I had lots of success when it come to publishing more complex artifacts. It would still worth looking more deeply into it if it's an important step in releasing your software.

**Comment by lacasseio** [comment]
Together with the Gradle team, we debug this further and it was a manipulation error. As I don't have a hand on a Solaris or HP-UX box, I tried faking it by changing the `os.name`. Unfortunately, the JDK has [custom check](https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/9a751dc19fae78ce58fb0eb176522070c992fb6f/jdk/src/solaris/classes/java/lang/UNIXProcess.java#L164) for that `os.name` and event aligning the expected name for Solaris, is uses a launch strategies that is incompatible with my environment. I was able to get all the way to the GCC forking so I'm assuming that it should work for your needs. I will work on merging the PR linked in my previous comment and cut a snapshot release for you to try.

**Comment by lacasseio** [comment]
I released version `0.4.127-202106101917.5d44175c` with the change above. That should unblock you to run on the same host. You may have to explicitly declare the toolchains. We currently rely on Gradle's software model for toolchain declaration so something like the following would force `Gcc` toolchain to target `SunOS` OS Family on `x86-64` architecture:

```
class ConfigureSolarisToolchains extends RuleSource {
	@Finalize
	void addToolChain(NativeToolChainRegistry toolChains) {
		toolChains.withType(Gcc) {
			target('sunosx86-64')
		}
	}
}

apply plugin: ConfigureSolarisToolchains
```

Note that target string is [composed out of the `TargetMachine`'s OS family and architecture name](https://github.com/nokeedev/gradle-native/blob/ca1c58dc1bc7b9bce17a362bb4086a1ff200eb81/subprojects/platform-native/src/main/java/dev/nokee/platform/nativebase/internal/NativePlatformFactory.java#L35). By default the host target machine is inferred from JVM property named `os.name`. Since we use this value as-is we may have to do some additional tweaking so don't hesitate to report back here and we will do any change that is required.

**Comment by lacasseio** [comment]
Note the Toolchain configuration uses a `RuleSource` plugin as it's easier to share between projects than using the `model` DSL.

**Comment by chittiraju** [comment]
Thanks alot mate.. i'll try it out immediately and revert back

**Comment by chittiraju** [comment]
Finally it compiled on HPUX and solaris:) 

Thanks a ton 👍 

Thanks for the toolchain configuration tip which you provided.

There was one more check which had to be modified in DefaultMachineArchitecture.java of runtimeNative
the arch of our HPUX machine is ia64n and that of solaris is sparcv9.
I have added these two arch to the source and compiled locally and patched it in the gradle cache and it worked. 
`public static DefaultMachineArchitecture forName(String name) {
		String archName = name.toLowerCase();
		if (asList("x86", "i386", "ia-32", "i686").contains(archName)) {
			return X86;
		} else if (asList("x86-64", "x86_64", "amd64", "x64").contains(archName)) {
			return X86_64;
		} else {
			return **new UnknownMachineArchitecture(archName);**
		}
	}`

I know its not the right way of handling. can you please handle it correctly. as the UnknownMachineArchitect.is32Bit() returns USOE exception. 

if there is any way if i can inject the architect and custom OS family from my application that would be great.

**Comment by chittiraju** [comment]
Is  nokee plugin not based on new variant based architecture of gradle native pluign?

assemble task doesnt create builds debug and release builds for the project can you also throw some light over this.

i see  binaries are created in exes/main directory not build variant dir.
How do i create variant based folders and publish them the way gradle native plugin does through maven-publish.

**Comment by lacasseio** [comment]
Yes, you are right, let me think about this more. I could add those architecture alias but those are just for convenience. What we want to aim for is provide a more complete modeling in term of instruction set, pointer size, endieness, and other processor features. Currently, the `is32Bit()` and `is64Bit()` are placeholders for pointer size which both supported architecture are Intel instruction set. In your case and for cases like Arm support, we want some convenience but also a richer way to declare the architecture. I will add more known architectures as well as some test coverage.

With regards to build variant directory, we only include the build variant information when the respective dimension is ambiguous. For example, if multiple different operating system are used, we will include it. But if only one operating system is used, we won't include it. In general, the binary's location should be accessed via the model instead of by path construction (i.e. `"$buildDir/exes/main/my-binary"`). You don't really need to create variant folder to publish them with a variant name. Right now, each variant has a `identifier` where you can query the `fullName`. This will include all variant name event if they are ambiguous. Unfortunately, that API is internal as we plan to change it a little bit. We understand that a quick access to the full variant name is useful, it opens the wrong discussion on how the name should be formated. Instead, we would prefer to provide an API that allow users to determine the name of a variant however they see fit for their needs. We may provide a default implementation but it's generally bad to depend on the name. Instead the build should depends on the properties of the variant in term os OS family, machine architecture, operating mode, etc. Each builds has a different needs so there is no "one size fit all". Regarding publication in Maven, the core native plugin uses the concept of a one main components that points to other components. Let me write a sample to mimic that behaviour with Nokee and get back to you.

**Comment by lacasseio** [comment]
One misconception that I often see is treating the `exes/main/<variant>` directories as the final resting place of the binaries. In other build system that would be a good assumption. With Nokee/Gradle, those directories as _a_ place where the binaries are outputted. Generally if the build needs to produce a specific on-disk layout, it would be a "packaging/install" steps that would Sync the binaries into the expected layout. That being said, we do want to provide a minimum configuration for changing the default on-disk layout but it should not be mixed with "packaging/installing" step. It is convenient to avoid additional copy work and mix compilation/linking with packaging/installing but Gradle has great work avoidance API so the cost is in fact quite low.

**Comment by lacasseio** [comment]
I created [this PR](https://github.com/nokeedev/gradle-native/pull/288) with more "well-known" OS/Arch names. Feel free to provide any feedback regarding the defaults. Once CI passes, I will cut a release for you to try.

**Comment by lacasseio** [comment]
I merged the PR but feel free to provide any feedback, I can do additional changes in other PR if something is wrong. You can give `0.4.137-202106111656.58c572f9` version a try.

**Comment by chittiraju** [comment]
World's fine thanks for a quick fix.

This fix is much refined. though TargetMachine configuration is from the cpp-application plugin extension for hpux and Solaris I still can go ahead without it.

Can you please help me out with a sample publishing/consuming with nokee plugin

**Comment by lacasseio** [comment]
You are right that `TargetMachine` for hpux and solaris needs to be created by name instead of having easier-to-use method calls. I will see if I can fix that.

Sorry for missing the publishing/consuming sample, I got pulled into other work. I will work on this and get something by tomorrow.

**Comment by chittiraju** [comment]
Can you please help me here

**Comment by lacasseio** [comment]
I wrote a first draft of the solution for publishing and pushed it here: https://github.com/nokeedev/native-component-publishing. There is a small issue with consuming the published binaries which I will address tomorrow. However, the general idea won't change. It publishes one artifact per variant and a central artifact that links everything together.

**Comment by lacasseio** [comment]
The publishing works for both library and application. I haven't tested it in more complex scenarios but I don't see why it wouldn't work. The project is a demonstration. There is some limitation but I tried to make it as flexible as possible. It will be one of the next features we work on and the feature will look very closely in terms of functionality to the code in the sample. Don't hesitate if you have more questions. We can also look at your specific scenario more closely to see how we can best use Nokee to improve your build.

**Comment by chittiraju** [comment]
thanks for the quick turnaround.
I see that the dependency for the app is implementation project(':lib') but not from the artifactory.  but that is not what we want for our project.

i have a small question regarding gradle plugin not nokee.
I have changed code of gradle-platform-native and compiled and patched just the fix that we done for the nokee plugin. but it throws no toolchain configured for HP-UX IA64N

```
No tool chain has support to build C++ for host operating system 'HP-UX' architecture 'IA64N':
    - Tool chain 'gcc' (GNU GCC):
        - Don't know how to build for host operating system 'HP-UX' architecture 'IA64N'.
```

i did apply the plugin that you earlier provided

```
class ConfigureHPUXToolchains extends RuleSource {
	@Finalize
	void addToolChain(NativeToolChainRegistry toolChains) {
		toolChains.withType(Gcc) {
			target('hpuxia64n')
		}
	}
}


apply plugin: ConfigureHPUXToolchains
```

still no luck.

**Comment by lacasseio** [comment]
With regards to `implementation project(':lib')`, the publishing is configured to publish in an on-disk repository which is essentially the same as Artifactory or any other Maven compatible repository. Once published, it is possible to switch the dependency to `implementation 'com.example.greeter:lib:4.2'` which will consume a remote coordinate in the local on-disk repository. It's also possible to point at a remote Artifactory to consume from there.

The core Gradle native only half-support the configuration of toolchains for other OS family/architecture. The issue is related to how core Gradle native maps the OS family/architecture name to a target for toolchain matching. It [always assumes the OS family is the host and only changes the architecture](https://github.com/gradle/gradle/blob/3ac8c7f9c0afab543391b47dfce3c1c89bf652d1/subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/internal/toolchains/DefaultToolChainSelector.java#L95-L97). In Nokee, we solved this (until we can roll a better toolchain selection), by [composing the OS family name and architecture name so we can select any toolchain definition](https://github.com/nokeedev/gradle-native/blob/ca1c58dc1bc7b9bce17a362bb4086a1ff200eb81/subprojects/platform-native/src/main/java/dev/nokee/platform/nativebase/internal/NativePlatformFactory.java#L34-L36). To make it work with Gradle core native support, you would either need to patch the above code or reconfigure the default toolchain based on the current OS running Gradle. Both aren't ideal.

**Comment by chittiraju** [comment]
Thats a great deal of change.

Thanks alot mate. calling it a day.. its nice working with you :)

cheers..

**Comment by lacasseio** [comment]
No worries, thanks for all the feedback. If you need any more help don't hesitate to reach out.

**Comment by lacasseio** [comment]
@chittiraju Just in case you are still planning to use Nokee for your native builds. I made some slight alteration to the canonical name to the known OS families. It shouldn't have an impact but just in case some toolchain starts to miss-aligns.
