### ISSUE TITLE
Depending on 3rd party binary which depends on another library

### ISSUE THREAD

**Issue by javenwang** [nokeedev/gradle-native#52]
Let's say we have `libcpp-greeter.so` which depends on `libcpp-sayer.so`. We want to write a JNI wrapper for `libcpp-greeter.so`. We have `build.gradle.kts` as below:
```kotlin
plugins {
    id("java")
    id("dev.nokee.jni-library")
    id("dev.nokee.cpp-language")
}
// ...
dependencies {
    nativeImplementation(files("lib/libcpp-greeter.so", "lib/libcpp-sayer.so"))
}
```

In the static block we load this library:
```java
public class Greeter {
    static {
        ClassLoader cl = Greeter.class.getClassLoader();
        NativeLoader.loadLibrary(cl, "cpp-sayer");
        NativeLoader.loadLibrary(cl, "cpp-greeter");
        // this is JNI binding which call function in libcpp-greeter.so
        NativeLoader.loadLibrary(cl, "jni-library-with-junit-test"); 
    }
}
```

when we run `./gradlew test` we will see the NPE error.

I'm not sure if it is related to #13

**Comment by lacasseio** [comment]
Thanks for the issue, to add ad-hoc files like this you would have to use consuming configuration instead of the bucket configuration. The buckets are the one that should used the majority of the time such as `nativeImplementation` (and with 0.4, `nativeRuntimeOnly`, `nativeLinkOnly`). Those can only use a project notation or external notation. It doesn't make sense to add files directly to them as each stage of the compilation will pick from the bucket configuration (compilation, linking and runtime). It basically means both shared libraries should be used as headers, link libraries and runtime libraries. I will improve the error handling around this use case https://github.com/nokeedev/gradle-native/issues/53.

If your components are built by Gradle, then it would be better to declare a dependency to the project. The transitivity should pick both of the libraries and automatically wire them inside the JNI JAR.

If the components aren't built by Gradle then you can use the [`JniLibrary#getNativeRuntimeFiles()`](https://nokee.dev/docs/nightly/javadoc/dev/nokee/platform/jni/JniLibrary.html#getNativeRuntimeFiles--) file collection to add ad-hoc files to the JNI JAR. This is only available in the nightly at the moment. The build script code should look like the following:

```
library {
    variants.configureEach {
        nativeRuntimeFiles.from(files("lib/libcpp-greeter.so", "lib/libcpp-sayer.so"))
    }
}
```

Both files will be added at the same resource location specified by [`JniLibrary#getResourcePath()`](https://nokee.dev/docs/nightly/javadoc/dev/nokee/platform/jni/JniLibrary.html#getResourcePath--).

To further improve the documentation, could you point me out where you would expect to find the information that would lead to the build script code sample above? I want to make sure the documentation is as complete as possible for anyone have the same or similar use cases. Would a sample showing this use case help?

**Comment by lacasseio** [comment]
I mentioned the native runtime files in the [building JNI project chapter](https://github.com/nokeedev/gradle-native/blob/master/subprojects/docs/src/docs/manual/building-jni-projects.adoc#native-runtime-files) as well as released a [new sample demonstrating the pre-built binaries scenario](https://github.com/nokeedev/gradle-native/tree/master/subprojects/docs/src/docs/samples/jni-library-with-pre-built-binaries). I believe it should be enough to solve this issue. I'm looking forward to your feedback.

**Comment by javenwang** [comment]
Hi @lacasseio , I still need to add something like `nativeImplementation` or JNI plugin wont set `java.library.path` correctly which then leads to "symbol lookup error" in runtime.

It would be better to have a new sample for this case.

In my case I want to to write a JNI wrapper for a native library provided by a 3rd party vendor. I don't have the source code which means I cannot build it by Gradle.

**Comment by lacasseio** [comment]
I see, that is a bug on my side. Thanks for telling me the details. I will make sure the native runtime files are properly configured into `java.library.path`.

**Comment by lacasseio** [comment]
I can also see some confusion from the JNI composing sample. I will add a not in there for prebuilt libraries.

Also,thinking about this a bit more, a previous comment was miss leading. It should be possible to use a file dependency in nativeRuntimeOnly bucket as well. That would should make sense. I will fix those problems today.

**Comment by lacasseio** [comment]
I didn't find any bug with regard to my understanding of the issue. I created the [following sample](https://github.com/nokeedev/gradle-native/tree/master/subprojects/docs/src/docs/samples/jni-library-composing-from-pre-built-binaries) that tries to reproduce as accurately as possible the use case and scenario. The sample in question generates a JNI library without any native source and using pre-built binaries. We can validate everything is wired properly by listing the files inside the JNI JAR and executing the unit test.

If you still see an issue with the latest nightly, it would be great if you could attach a sample to reproduce the bug.

**Comment by lacasseio** [comment]
If you still have an problem, please open another issue.
