### ISSUE TITLE
Gradle API JARs are not true MR-JARs

### ISSUE THREAD

**Issue by aalmiray** [nokeedev/gradle-native#746]
See original issue at https://github.com/gradle/gradle/issues/23002

If Nokee is responsible for creating the JARs then I'd ask to follow the MR-JARs structure going forward, as once JARs have been published to Maven Central they can't be changed. 

OTOH if the JARS are create by Gradle itself then I'd ask to let them know they are doing it wrong. 

Thanks.

**Comment by lacasseio** [comment]
Not sure what `OTOH` means and what the "MR-JARs structure" is supposed to mean here. In the future, please provide more information than just a link to the other issue, so this can be actionable. More information is provided on the Gradle issue; Nokee issues should be held to the same standard. You're welcome to [refer to the packaging of those JARs](https://github.com/gradle-plugins/gradle-api) and give us specific changes that we can make to improve the JARs.

The repackaging tries to publish what Gradle generates via `gradleApi()` and `gradleTestKit()`. The process generates sensible POM/module files to include dependencies Groovy and Kotlin. It also tries its best to package the sources into a sensible source JAR. The process doesn't move anything, creates new files, etc. The goal was to access API JARs "as-if there were generated locally". The current situation is similar to what you would generally get with Gradle. More specifically, it's better than vanilla Gradle because you can target any Gradle version separated from the currently running Gradle. But it's worse than vanilla Gradle if you hit some particular edge cases, mainly around the opinionated internal implementation of how Gradle finds itself (when using internal API). 

We would love to be able to modulize the Gradle API, such as splitting the internal vs public APIs or fix some strangeness with older Gradle classes. However, it would require a much deeper analysis of the Gradle API JARs, which would be very fragile. 

As for "once JARs have been published to Maven Central they can't be changed", the answer is yes and no. We can't change the JAR, which is fine, but we can do a patch release. We didn't have to do that yet, but if we had to, we would append `-<patch>` to the version. The usual way to consume those JAR should be via the toolbox plugins, which would be made aware of those patches.

**Comment by lacasseio** [comment]
Reading the [Gradle issue](https://github.com/gradle/gradle/issues/23002) in more detail, I don't believe it's a problem with the redistribution of the JARs. It works as intended, meaning "offering the generated Gradle API JARs as external dependencies". Any generation issues should be aimed at Gradle. Unless there is a foolproof way we can fix the outlined issues during the redistribution, we can't risk making any modifications that could break the parity of the JAR with vanilla Gradle API.

If you happen to have more information or any actionable change to the process itself, then feel free to open another issue.
